package com.zombie.anomalous.registry

import com.zombie.anomalous.Anomalous
import xyz.xenondevs.nova.addon.registry.ItemRegistry
import xyz.xenondevs.nova.initialize.Init
import xyz.xenondevs.nova.initialize.InitStage

@Init(stage = InitStage.PRE_PACK)
object Items : ItemRegistry by Anomalous.registry {
    val LOGO = registerItem("logo")
    val GATE_A_SIGN  = registerItem("gate_a_sign")
    val HCZ_SIGN = registerItem("hcz_sign")
    val EZ_SIGN = registerItem("ez_sign")

    val ROAD = registerItem(Blocks.ROAD)
    val ROAD_MIDDLE = registerItem(Blocks.ROAD_MIDDLE)
    val STEEL_RAILING = registerItem(Blocks.STEEL_RAILING)
    val COPPER_PIPE = registerItem(Blocks.COPPER_PIPE)
    val CC_CAMERA = registerItem(Blocks.CC_CAMERA)
    val CEILING_TILE = registerItem(Blocks.CEILING_TILE)
    val WEAPON_DESK_FOOT = registerItem(Blocks.WEAPON_DESK_FOOT)
    val WEAPON_DESK_DESK_MONITOR = registerItem(Blocks.WEAPON_DESK_MONITOR)
    val WEAPON_DESK_DESK_PLATE = registerItem(Blocks.WEAPON_DESK_PLATE)
    val COPPER_DIAMOND_PLATE = registerItem(Blocks.COPPER_DIAMOND_PLATE)
    val CERAMIC_TILES = registerItem(Blocks.CERAMIC_TILES)
    val LIGHT = registerItem(Blocks.LIGHT)
    val LIGHT_SMALL = registerItem(Blocks.LIGHT_SMALL)
    val LIGHT_LONG = registerItem(Blocks.LIGHT_LONG)
    val ROUND_CONCRETE_WALL_BOTTOM = registerItem(Blocks.ROUND_CONCRETE_WALL_BOTTOM)
    val ROUND_CONCRETE_WALL_MIDDLE = registerItem(Blocks.ROUND_CONCRETE_WALL_MIDDLE)
    val ROUND_CONCRETE_WALL_TOP = registerItem(Blocks.ROUND_CONCRETE_WALL_TOP)
    val SCREEN = registerItem(Blocks.SCREEN)
    val SERVER_TOP = registerItem(Blocks.SERVER_TOP)
    val SERVER_BOTTOM = registerItem(Blocks.SERVER_BOTTOM)
    val TRIMMED_GLASS = registerItem(Blocks.TRIMMED_GLASS)
    val EZ_SLOPED_WALL = registerItem(Blocks.EZ_SLOPED_WALL)
    val THIN_CONCRETE_WALL = registerItem(Blocks.THIN_CONCRETE_WALL)
    val VENT = registerItem(Blocks.VENT)
    val SC_WALL = registerItem(Blocks.SC_WALL)
    val EZ_WALL = registerItem(Blocks.EZ_WALL)
    val EZ_TRIMMED_WALL = registerItem(Blocks.EZ_TRIMMED_WALL)
    val EZ_LINED_WALL = registerItem(Blocks.EZ_LINED_WALL)
    val CONCRETE_WALL = registerItem(Blocks.CONCRETE_WALL)
    val CONCRETE_CORNER = registerItem(Blocks.CONCRETE_CORNER)
    val CONCRETE_PILLAR = registerItem(Blocks.CONCRETE_PILLAR)
    val WHITE_PIPE = registerItem(Blocks.WHITE_PIPE)
    val CONCRETE_RAILING = registerItem(Blocks.CONCRETE_RAILING)
    val DRAIN_COVER = registerItem(Blocks.DRAIN_COVER)
    val ROUND_CONCRETE_WALL_SLAB = registerItem(Blocks.ROUND_CONCRETE_WALL_SLAB)
    val COPPER_DIAMOND_PLATE_SLAB = registerItem(Blocks.COPPER_DIAMOND_PLATE_SLAB)
    val CERAMIC_TILES_SLAB = registerItem(Blocks.CERAMIC_TILES_SLAB)
    val SC_WALL_SLAB = registerItem(Blocks.SC_WALL_SLAB)
    val COPPER_DIAMOND_PLATE_STAIR = registerItem(Blocks.COPPER_DIAMOND_PLATE_STAIR)
    val CERAMIC_TILES_STAIR = registerItem(Blocks.CERAMIC_TILES_STAIR)
    val SC_WALL_STAIRS = registerItem(Blocks.SC_WALL_STAIRS)
    val SWITCH_CLOSED = registerItem(Blocks.SWITCH_CLOSED)
    val SWITCH = registerItem(Blocks.SWITCH)
    val TUNNEL_TOP = registerItem(Blocks.TUNNEL_TOP)
    val TUNNEL_BOTTOM = registerItem(Blocks.TUNNEL_BOTTOM)
    val INTERCOM_SPEAKER = registerItem(Blocks.INTERCOM_SPEAKER)
    val ZONE_WALL = registerItem(Blocks.ZONE_WALL)
    val ZONE_WALL_CORNER = registerItem(Blocks.ZONE_WALL_CORNER)
    val HZ_WALL_CORNER = registerItem(Blocks.HZ_WALL_CORNER)
    val HZ_WALL_SLOPE = registerItem(Blocks.HZ_WALL_SLOPE)
    val HZ_WALL = registerItem(Blocks.HZ_WALL)
}